[phases.setup]
nixPkgs = ["python39", "ollama"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "python -c \"import nltk; nltk.download('punkt'); nltk.download('stopwords')\""
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "bash -c 'ollama serve & sleep 10 && ollama pull llama3.1:8b && uvicorn backend.main:app --host 0.0.0.0 --port $PORT'"